[package]
name = "shard_state_processing"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dependencies]
tree_hash = { path = "../utils/tree_hash" }
types = { path = "../types" }

