[package]
name = "shard_store"
version = "0.1.0"
authors = ["will <wvillanu89@gmail.com>"]
edition = "2018"

[dev-dependencies]
tempfile = "3"

[dependencies]
db-key = "0.0.5"
leveldb = "0.8.4"
parking_lot = "0.7"
eth2_ssz = "0.1"
eth2_ssz_derive = "0.1"
tree_hash = "0.1"
types = { path =  "../../eth2/types" }
lazy_static = "1.3.0"
lighthouse_metrics = { path = "../../eth2/utils/lighthouse_metrics" }
